### ISSUE TITLE
No results for search via scene List

### ISSUE THREAD

**Issue by FabianVista** [olivierhagolle/LANDSAT-Download#11]
Hi Olivier, 
thanks for this tool, I think it will help me a lot for automating processes in future. At the moment I just have a problem downloading files via the scene list. Searching with "python download_landsat_scene.py -o liste -l SceneList.txt -u usgs.txt --output /home/user/DownloadData" delivers only "None None" as a result for example for the scene list: 
Germany LC81940262015043LGN00
Germany LC81930272015036LGN00

Any Ideas why the script is not working in this case?
Thanks,
Fabian

**Comment by olivierhagolle** [comment]
Thanks Fabian,
 There were indeed a few bugs in the liste mode.
An indentation problem, and then an error in the url.
The scene mode is used more often, this bug must have been there for a long time....

Please try it now, I hope it will work.
Olivier

**Comment by FabianVista** [comment]
Thanks for the quick fix, Olivier!
Works like charm now!
