### ISSUE TITLE
Cannot download LE7 for circa 2005

### ISSUE THREAD

**Issue by crianopa** [olivierhagolle/LANDSAT-Download#18]
Hi guys,

Thanks for the code, it is saving me a lot of time. I am downloading data for years 2000 and 2005.
There is not problem downloading the list of 2000. However the scenes of 2005 are not processed. 
I made click on the link and EarthExplorer return this error:  "Download Not Found. Invalid scene selection". 
Any solution?
I am attaching the list of 2005
[list2005.txt](https://github.com/olivierhagolle/LANDSAT-Download/files/53690/list2005.txt)

This is part of the process:
xxxxx@xxxxx/LANDSAT-Download-58d28f2$ python download_landsat_scene.py -o liste -l list.txt -u usgs.txt --output ../LE7                                     
None None
LE71700582005303ASN00
url= http://earthexplorer.usgs.gov/download/3372/LE71700582005303ASN00/STANDARD/EE
Establishing connection to Earthexplorer...
LE71700582005335ASN00
url= http://earthexplorer.usgs.gov/download/3372/LE71700582005335ASN00/STANDARD/EE
Establishing connection to Earthexplorer...
LE71700582006034ASN00
url= http://earthexplorer.usgs.gov/download/3372/LE71700582006034ASN00/STANDARD/EE
Establishing connection to Earthexplorer...

Thanks 
Carlos Riano

**Comment by crianopa** [comment]
I found the error... The repertory for LE7 foor those years is not 3372 but it is 3373. I changed in the line 544 and now it works.

Carlos Riano

**Comment by olivierhagolle** [comment]
Thanks Carlos !
It was in the Readme actually.
Olivier
