### ISSUE TITLE
L8 download not working

### ISSUE THREAD

**Issue by unnic** [olivierhagolle/LANDSAT-Download#20]
Hello,

I've been using the LANDSAT-Download tool and it worked very well until a couple of days ago. 
I reveice an Error:
```
http://earthexplorer.usgs.gov/download/4923/LC81900272016066LGN00/STANDARD/EE
erreur : le fichier est au format html
```
[and then some html file]

Any Ideas why this error comes up or how I could solve it?

Thanks for your work.

**Comment by olivierhagolle** [comment]
That's true, it seems it is not working anymore.  I do not exactly get the same error as you do:
`>python` download_landsat_scene.py -o scene -b LC8 -d 20160127 -s 198030 -u usgs.txt
http:///ers.cr.usgs.gov/download/4923/LC81980302016042LGN00/STANDARD/EE
URL Error: no host given http:///ers.cr.usgs.gov/download/4923/LC81980302016042LGN00/STANDARD/EE
http:///ers.cr.usgs.gov/download/4923/LC81980302016042LGN01/STANDARD/EE
URL Error: no host given http:///ers.cr.usgs.gov/download/4923/LC81980302016042LGN01/STANDARD/EE
http:///ers.cr.usgs.gov/download/4923/LC81980302016042LGN02/STANDARD/EE
URL Error: no host given http:///ers.cr.usgs.gov/download/4923/LC81980302016042LGN02/STANDARD/EE
Searching for images on (julian date): 2016058...
http:///ers.cr.usgs.gov/download/4923/LC81980302016058LGN00/STANDARD/EE
URL Error: no host given http:///ers.cr.usgs.gov/download/4923/LC81980302016058LGN00/STANDARD/EE
http:///ers.cr.usgs.gov/download/4923/LC81980302016058LGN01/STANDARD/EE
URL Error: no host given http:///ers.cr.usgs.gov/download/4923/LC81980302016058LGN01/STANDARD/EE
http:///ers.cr.usgs.gov/download/4923/LC81980302016058LGN02/STANDARD/EE
URL Error: no host given http:///ers.cr.usgs.gov/download/4923/LC81980302016058LGN02/STANDARD/EE

They must have changed something on the server, but I did not find what it is so far.
Best regards,
Olivier

**Comment by olivierhagolle** [comment]
OK I found out, they changed the URL to download products from
http://ers.cr.usgs.gov/download

To http://earth

**Comment by unnic** [comment]
seems to work with the updated .py file.
