### ISSUE TITLE
Error : urlerror urlopen error errno 11001 getaddrinfo failed

### ISSUE THREAD

**Issue by yogitakarale** [olivierhagolle/LANDSAT-Download#32]
I am getting following error when I try to run this "download_landsat_scene.py -o scene -b LC8 -d 20130127 -s 198030 -u usgs.txt -p proxy.txt --output C:/Python27/tmp/Landsat/"

urlerror urlopen error errno 11001 getaddrinfo failed

Any suggestions how to resolve this?

**Comment by olivierhagolle** [comment]
Hi,
There seems to be an issue with the proxy option. Do you need to go through a proxy ? 
The script usually works without the proxy option if you set the proxy_http system variables.  At least on Linux.
Olivier

**Comment by yogitakarale** [comment]
Thanks Oliver! It worked well after removing proxy option.
