### ISSUE TITLE
urllib2.HTTPError: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by mrjohnston** [olivierhagolle/LANDSAT-Download#33]
Good evening Olivier,

Thank you very much for sharing this script! I'm a first-time user, and I've been running into an HTTP Error 503. At the moment, I'm just testing things out by using your README example, with no proxy and my own usgs.txt file:

 **download_landsat_scene.py -o scene -b LC8 -d 20130127 -s 043034 -u usgs.txt --output /home/miriam/Documents/test/**

The full error is: 

None None
Traceback (most recent call last):
  File "download_landsat_scene.py", line 594, in <module>
    main()
  File "download_landsat_scene.py", line 412, in main
    connect_earthexplorer_no_proxy(usgs)	
  File "download_landsat_scene.py", line 79, in connect_earthexplorer_no_proxy
    f = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

Generally, I think a 503 error would signal some issue with the webpage itself, but I can sign in just fine using a browser, and a quick check with curl (curl -I "https://ers.cr.usgs.gov/login") says "HTTP/1.1 200 OK."

Do you know what the source of this issue may be? Many thanks, in advance. I really appreciate your help.

**Comment by fomoto** [comment]
Good morning.
I got the same error. This also started 3 days ago.
Tried urllib2, requests and mechanize but none of them work.

**Comment by burt46** [comment]
Me too. Something has changed via the USGS end. 

Reading something similar elsewhere that occurred for Amazon, its possible that automated access to the USGS servers are being blocked. 

See the answers in the following Stackoverflow link

[http://stackoverflow.com/questions/25936072/python-urllib2-httperror-http-error-503-service-unavailable-on-valid-website]

**Comment by burt46** [comment]
Thanks Olivier, its a shame they keep changing things. I use your script on a weekly basis and its saved me a great deal of time.

I am not a programmer or i would help to support this project. I hope you or someone here can find time to update the script in the near future.

Many thanks

**Comment by neilflood** [comment]
I just thought I would add, I have a similar download script which has run into exactly the same problem. I have tested curl, but could not get that to work, and have also tested the suggestion above from StackOverflow, about faking the User-Agent, but this did not seem to help, either. 

One half-baked solution is to do the login step manually in a browser, and save the cookies into a file. This can then be loaded into wget using the --load-cookies option. This works fine. Not quite fully automated, but still better than nothing. The cookie will expire eventually, of course. 

It also seems that they have moved the bulk metadata files to a slightly different URL. In this new location, the Collection-1 version are old copies, for some reason. I use the XML copies, so have not checked the CSV version. I have notified them of this, and they responded quickly, saying that they are still getting that organised. The new URL is https://landsat.usgs.gov/landsat/metadata_service/bulk_metadata_files/. 

Many thanks to Olivier, as always. :-)

**Comment by olivierhagolle** [comment]
Thanks for the feedback, Neil (and nice to hear from you !) 
I did the same yesterday evening (curl, user-agent), nothing worked either.
I have always wanted to avoid google-cloud or amazon, but now, I still need to access the data...
Cheers,
Olivier

**Comment by mrjohnston** [comment]
Thank you very much, all, for your help with this! I'll stay tuned & also see what I can do through google-cloud, though I hear Olivier on this issue...

Best,
Miriam

**Comment by olivierhagolle** [comment]
Problem solved by one of my colleagues at CNES/THEIA/MUSCATE !
The script works if we remove "/login" within "https://ers.cr.usgs.gov/login" and replace every "http" by "https".  I also changed the address for the metadata files as suggested by Neil (but did not test it yet).

So, see my coming commit (in a few minutes), and don't go to google  ;)
Cheers,
Olivier

**Comment by mrjohnston** [comment]
Thanks very much! The script is now working well for me.

**Comment by neilflood** [comment]
Brilliant! That change works for me, too. My thanks to Olivier and colleagues.
