### ISSUE TITLE
What is necessary to get Landsat 5 and 7?

### ISSUE THREAD

**Issue by vascobnunes** [olivierhagolle/LANDSAT-Download#4]
First of all, congratulations on your script. It will certainly be of much help to me.
I was able to download LC8 images, but could get images with dates previous to Landsat 8 being operational. 
Also, suggestion for future improvement: automatically unpack the tgz files... Maybe I can even try to help you with that if you're interested.
Thanks

**Comment by mrwooten** [comment]
Hi Olivier,
Thanks so much for this script. I'm trying to implement an automatic landsat download into an automated decision support system for wildfire relief and this code may be exactly what I need. However, I really do need this get all existing landsat scenes for a particular time period, and I need for the process to be as automated as possible, so I was wondering, how could I create a similar script that will first order the files that are not online and then download them, in addition to everything that is online? I'm looking into python packages that can allow me to programmatically interact with the Landsat ordering form, but I'm new to web-services programming so I figured I'd ask you for advice first. Any ideas? Also, you say we can order them first then use the script to download. Does the script need to be changed to accommodate the ordered files or once the order is placed, are the files just online, enabling the script to grab them?
Thanks much!

**Comment by olivierhagolle** [comment]
Thanks mrwooten, I am happy the tool is useful. Once the files are ordered, they are put on the disks for a while, and the Landsat Download tool should succeed in downloading the files. But having an automatic ordering tool seems complicated, and I am really not an expert in web services...

However, there might be another tool on github that manages to do that, but I did not try it.
 https://github.com/developmentseed/landsat-util

Cheers,
Olivier
