### ISSUE TITLE
Not able to download data

### ISSUE THREAD

**Issue by llin-csiss** [olivierhagolle/LANDSAT-Download#47]
Thanks for the code!
I am first time user but failed to use the script, here is my script and error:
 **python ./download_landsat_scene.py -o scene -s 100062 -b LC8 --dir 12864 --station 'LGN' -d 20180321 -u usgs.txt**

and the error:
**LGN 12864
Searching for images on (julian date): 2018081...
https://earthexplorer.usgs.gov/download/12864/LC81000622018081LGN00/STANDARD/EE
URL Error: [Errno 8] _ssl.c:480: EOF occurred in violation of protocol https://earthexplorer.usgs.gov/download/12864/LC81000622018081LGN00/STANDARD/EE**

in the output file only one log.txt with [] inside.

I tried one of the links in browser (for example:https://earthexplorer.usgs.gov/download/12864/LC81000622018081LGN00/STANDARD/EE) and it works perfect, and the download started after I input my credential. 
Not sure what I am doing wrong. Any help is great appreciated!!!

**Comment by olivierhagolle** [comment]
I tried this on my side, and it works. Difficult to help you... Maybe an issue in your password information within usgs.txt, or some specificity and additional controls in your network ? Or just a temporary issue at USGS ?

```>python ./download_landsat_scene.py -o scene -s 100062 -b LC8 --dir 12864 --station 'LGN' -d 20180321 -u usgs.txt
LGN 12864
Searching for images on (julian date): 2018081...
https://earthexplorer.usgs.gov/download/12864/LC81000622018081LGN00/STANDARD/EE
LC81000622018081LGN00.tgz 1001282129
Downloading LC81000622018081LGN00.tgz (954.9 MB):
[                                                  ]  1% 9.5 MBps
```

**Comment by llin-csiss** [comment]
I tried another computer at home, and it went through the code without an issue. only problem is it does not actually download data like the one shown in your code. Mine is like following:

python ./download_landsat_scene.py -o scene -s 100062 -b LC8 --dir 12864 --station 'LGN' -d 20180321 -u usgs.txt --output ./tmp 
'LGN' 12864 
Searching for images on (julian date): 2018081...
https://earthexplorer.usgs.gov/download/12864/LC81000622018081'LGN'00/STANDARD/EE
https://earthexplorer.usgs.gov/download/12864/LC81000622018081'LGN'01/STANDARD/EE
https://earthexplorer.usgs.gov/download/12864/LC81000622018081'LGN'02/STANDARD/EE
Searching for images on (julian date): 2018097...
https://earthexplorer.usgs.gov/download/12864/LC81000622018097'LGN'00/STANDARD/EE
https://earthexplorer.usgs.gov/download/12864/LC81000622018097'LGN'01/STANDARD/EE
https://earthexplorer.usgs.gov/download/12864/LC81000622018097'LGN'02/STANDARD/EE

**Comment by llin-csiss** [comment]
I have solved this by add '/' in the end of my script.
Many thanks for your help!

**Comment by olivierhagolle** [comment]
:+1:
