### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by wukongtea** [olivierhagolle/LANDSAT-Download#53]
It dosen't work in python3，can you repair it?

F:\Landsat>python download_landsat_scene.py -o scene -b LC8 -d 20130127 -s 198030 -u usgs.txt --output /data
  File "download_landsat_scene.py", line 3
    Landsat Data download from earth explorer
    ^
IndentationError: unexpected indent

F:\Landsat>python download_landsat_scene.py -o scene -b LC8 -d 20130127 -s 198030 -u usgs.txt --output /data
  File "download_landsat_scene.py", line 22
    print "Establishing connection to Earthexplorer with proxy..."
                                                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Establishing connection to Earthexplorer with proxy...")?

F:\Landsat>python download_landsat_scene.py -o scene -b LC8 -d 20130127 -s 198030 -u usgs.txt --output /data
  File "download_landsat_scene.py", line 22
    print "Establishing connection to Earthexplorer with proxy..."
Can you turn your python2 code into python3？

**Comment by olivierhagolle** [comment]
Hi
Some basic politeness would help... 
I will do it one day or the other, but not in my top priorities. Feel free to contribute ;)
Olivier

**Comment by wukongtea** [comment]
Sorry, it is my faults.Thank you very much for your kindness.
