### ISSUE TITLE
Encryption of the username and password file

### ISSUE THREAD

**Issue by vascobnunes** [olivierhagolle/LANDSAT-Download#7]
Oliver,
I think it would be important to have some sort of encryption to the usgs.txt file, because it will contain your credentials and is easily accessed.
Maybe an enhancement for version 1.1.0? :)
Regards.

**Comment by liangzhengai** [comment]
Thank for your effort.
I've used your project very well. 
And your advice is useful.

**Comment by olivierhagolle** [comment]
Hi.
yes it would be an improvement for security, I am not sure the EarthExplorer password is that precious, but it would be very important concerning the proxy password. But I am afraid I do not know how to do that. Feel free to add it if you want !
Olivier
