### ISSUE TITLE
Function for Automatically generate Product List and Download?

### ISSUE THREAD

**Issue by liangzhengai** [olivierhagolle/LANDSAT-Download#8]
Hello!
Your product works well...

Um... I have a problem when I'm using your product.

I wish the function which generates the all available product list and download automatically, if i provide the date and wrs2 scene range.

for example)
If i had provided the parameters as follow

scene range : (100, 30) - (150, 60)
date : 2010/01/01 later

then all available products would be downloaded.

Can you help me?

I want you improve the speed of downloading.

Thanks you.

**Comment by olivierhagolle** [comment]
Hi Liangzhengai !
As you can give the WRS2 coordinates as argument in the command line, I think that you should be able to write a script that makes a loop for all the scenes you would like to download. I do not think it is necessary to complicate the script.
best regards,
Olivier
